version: 2
jobs:
  build:
    docker:
      - image: docker:dind
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Build Docker Image
          command: docker build --tag api:$(cut -c-8 dist/COMMITHASH) .
